kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dbaas-metrics-exporter
rules:
- apiGroups:
  - quota.openshift.io
  resources:
  - clusterresourcequotas
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - objectbucket.io
  resources:
  - objectbuckets
  verbs:
    - get
    - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
    - get
    - list
