kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dbaas-metrics-svc
rules:
 - apiGroups:
   - ""
   resources:
    - services
    - endpoints
    - pods
   verbs:
    - get
    - list
    - watch
