---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dbaas-metrics-exporter
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - quota.openshift.io
  resources:
  - clusterresourcequotas
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - objectbucket.io
  resources:
  - objectbuckets
  verbs:
    - get
    - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
    - get
    - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dbaas-metrics-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dbaas-metrics-exporter
subjects:
- kind: ServiceAccount
  name: dbaas-metrics-exporter
  namespace: openshift-dbaas-operator
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dbaas-metrics-svc
  namespace: openshift-dbaas-operator
rules:
 - apiGroups:
   - ""
   resources:
    - services
    - endpoints
    - pods
   verbs:
    - get
    - list
    - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dbaas-metrics-svc
  namespace: openshift-dbaas-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dbaas-metrics-svc
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
---
