apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      type: dbaas-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
        type: dbaas-operator
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        - --log-level=INFO
        image: controller:latest
        name: manager
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 20
        resources:
          limits:
            cpu: 200m
            memory: 1500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: INSTALL_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AUTH_TYPE
          valueFrom:
            secretKeyRef:
              key: AUTH_TYPE
              name: dbaas-operator-dev-prom-remote-write
              optional: true
        - name: RHOBS_API_URL
          valueFrom:
            secretKeyRef:
              key: RHOBS_API_URL
              name: dbaas-operator-dev-prom-remote-write
              optional: true
        - name: RH_SSO_TOKEN_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: RH_SSO_TOKEN_ENDPOINT
              name: dbaas-operator-dev-prom-remote-write
              optional: true
        - name: RHOBS_TOKEN
          valueFrom:
            secretKeyRef:
              key: RHOBS_TOKEN
              name: dbaas-operator-dev-prom-remote-write
              optional: true
        - name: ADDON_NAME
          valueFrom:
            secretKeyRef:
              key: ADDON_NAME
              name: dbaas-operator-dev-prom-remote-write
              optional: true
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
