apiVersion: v1
kind: Service
metadata:
  name: dbaas-metric-exporter
  namespace: openshift-dbaas-monitoring
  labels:
    app.kubernetes.io/component: dbaas-metric-exporter
    app.kubernetes.io/name: dbaas-metric-exporter
    app: dbaas-prometheus
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: exporter
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app.kubernetes.io/component: dbaas-metric-exporter
    app.kubernetes.io/name: dbaas-metric-exporter
    app: dbaas-prometheus