apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dbaas-prometheus
    app.kubernetes.io/component: dbaas-metric-exporter
    app.kubernetes.io/name: dbaas-metric-exporter
  name: dbaas-metric-exporter
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: exporter
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: dbaas-prometheus
    app.kubernetes.io/component: dbaas-metric-exporter
    app.kubernetes.io/name: dbaas-metric-exporter
  type: ClusterIP
status:
  loadBalancer: {}
