apiVersion: v1
kind: Service
metadata:
  labels:
    app: dbaas-prometheus
    control-plane: controller-manager
  name: controller-manager-metrics-service
  namespace: system
spec:
  ports:
  - name: metrics
    port: 8443
    targetPort: metrics
  selector:
    control-plane: controller-manager
