# permissions for end users to edit dbaastenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbaastenant-editor-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaastenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaastenants/status
  verbs:
  - get
