# permissions for end users to view dbaastenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbaastenant-viewer-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaastenants
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaastenants/status
  verbs:
  - get
