apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: addon-dbaas-operator-catalog
  namespace: redhat-dbaas-operator
spec:
  sourceType: grpc
  image: quay.io/osd-addons/dbaas-operator-index@sha256:f7bd64974ab6c2d4e055fdd5de7939961db2306e28282350d34c9ddb85bbb50c
  displayName: DBaaS Operator
