apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/dbaas-operator.openshift-dbaas-operator: ""
  name: dbaas-operator
  namespace: openshift-dbaas-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: dbaas-operator
  source: dbaas-operator
  sourceNamespace: openshift-marketplace

