apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/dbaas-operator.openshift-dbaas-operator: ""
  name: dbaas-operator
  namespace: openshift-dbaas-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: dbaas-operator
  source: dbaas-operator
  sourceNamespace: openshift-marketplace
  config:
    env:
      - name: ADDON_NAME
        value: dbaas-operator-dev
      - name: RHOBS_AUTH_TYPE
        value: dex
      - name: RHOBS_API_URL
        value: https://observatorium-observatorium.apps.mmikhail-obs1.kni.syseng.devcluster.openshift.com/api/metrics/v1/test2/api/v1/receive

