apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: dbaas-operator
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/rh_ee_mrudraia/dbaas-operator-catalog:v0.2.12
  displayName: DBaaS Operator