apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: dbaas-operator
  namespace: olm
spec:
  sourceType: grpc
  image: quay.io/tchughesiv/dbaas-operator-catalog:v0.2.0-eks
  displayName: DBaaS Operator