apiVersion: v1
kind: Namespace
metadata:
 name: redhat-dbaas-operator

---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: addon-dbaas-operator-catalog
  namespace: redhat-dbaas-operator
spec:
  sourceType: grpc
  image: quay.io/ecosystem-appeng/dbaas-operator-catalog:v0.5.0
  displayName: OpenShift Database Access

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: redhat-layered-product-og
  namespace: redhat-dbaas-operator

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: addon-dbaas-operator
  namespace: redhat-dbaas-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: dbaas-operator
  source: addon-dbaas-operator-catalog
  sourceNamespace: redhat-dbaas-operator
  startingCSV: dbaas-operator.v0.3.0
#  startingCSV: dbaas-operator.v0.4.0
