apiVersion: v1
kind: Namespace
metadata:
 name: redhat-dbaas-operator
spec:
 finalizers:
   - kubernetes

---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: addon-dbaas-operator-catalog
  namespace: redhat-dbaas-operator
spec:
  sourceType: grpc
  image: quay.io/osd-addons/dbaas-operator-index@sha256:f7bd64974ab6c2d4e055fdd5de7939961db2306e28282350d34c9ddb85bbb50c
  displayName: DBaaS Operator

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: dbaas-operator-group
  namespace: redhat-dbaas-operator

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/dbaas-operator.openshift-dbaas-operator: ""
  name: addon-dbaas-operator
  namespace: redhat-dbaas-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: dbaas-operator
  source: addon-dbaas-operator-catalog
  sourceNamespace: redhat-dbaas-operator
  config:
    env:
      - name: ADDON_NAME
        value: dbaas-operator-dev
      - name: RHOBS_AUTH_TYPE
        value: dex
      - name: RHOBS_API_URL
        value: https://observatorium-observatorium.apps.mmikhail-obs1.kni.syseng.devcluster.openshift.com/api/metrics/v1/test2/api/v1/receive
