---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: missing-provider-access
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: missing-provider-access
subjects:
- kind: Group
  name: system:serviceaccounts:openshift-dbaas-operator
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: missing-provider-access
  apiGroup: rbac.authorization.k8s.io