name: Build Image

on:
  push:
    branches:
    - main
    - release-*
    tags:
      - '*'
  pull_request:
    branches:
    - main
    - release-*

env:
  REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWOR }}
  REGISTRY_ORG: tchughesiv

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Image build
      uses: redhat-actions/buildah-build@v2
      id: build-image
      with:
        image: dbaas-operator
        platforms: linux/amd64
        tags: ${{ github.sha }}
        containerfiles: |
          ./Dockerfile

    - name: Log in to Quay.io
      uses: redhat-actions/podman-login@v1
      id: quay-login
      with:
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
        registry: quay.io

    - name: Image push
      uses: redhat-actions/push-to-registry@v2
      id: push-to-quay
      with:
        registry: ${{ steps.quay-login.outputs.registry }}/${{ env.REGISTRY_ORG }}
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"